### ISSUE TITLE
Are students from other schools accepted to contribute to the content?

### ISSUE THREAD

**Issue by ywh555hhh** [ustclug/Linux201-docs#30]
Dear USTCLUG members,

I am a student from Nanchang University (NCU), currently managing around 20 servers in our laboratory. I came across your Linux201 project and am excited about the initiative. I would like to inquire if students from other universities are allowed to contribute to the project documentation. I am eager to offer my help and will ensure that I adhere to the contribution standards.

Even if Linux201 is an internal project, I am still willing to share my experiences and information about the servers I manage, as well as any challenges I’ve encountered, to help enrich the content of the project.

Could you please let me know if external contributions are accepted? I look forward to your response.

Best regards,

**Comment by iBug** [comment]
Hi @ywh555hhh, we welcome all kinds of contributions from anyone interested. In fact, Linux 201 was never intended to be an "internal project". It is only true that it *started* from internal needs of USTCLUG.

If you can submit pull requests here, we'll be happy to review your contributions and help you adapt to our quality standards.

**Comment by ywh555hhh** [comment]
> Hi @ywh555hhh, we welcome all kinds of contributions from anyone interested. In fact, Linux 201 was never intended to be an "internal project". It is only true that it _started_ from internal needs of USTCLUG.
> 
> If you can submit pull requests here, we'll be happy to review your contributions and help you adapt to our quality standards.

I got it, thank you for your kindness!
