### ISSUE TITLE
建议开设小型机房运维技术交流渠道

### ISSUE THREAD

**Issue by ywh555hhh** [ustclug/Linux201-docs#36]
感谢 linux201 项目为小型机房运维提供的帮助。我在运维日常过程中遇到一些问题的时候往往找不到人交流与讨论，想请问 USTC LUG 是否有针对这类问题的专门群聊或频道？如果没有，是否有计划开设一个让大家讨论小型机房运维的技术交流平台？😭

**Comment by tiankaima** [comment]
也许可以去 https://lug.ustc.edu.cn/wiki/lug/contact/#telegram-%E4%B8%8A%E7%9A%84-lug 碰碰运气。
